"""Shared telemetry state used only to build analysis lap samples."""
import copy

DEFAULT_TELEMETRY_STATE = {
    "speed": 0, "throttle_raw": 0.0, "brake_raw": 0.0,
    "current_lap_time_ms": 0,
    "last_lap_time_ms": 0, "lap_number": 0, "lap_distance": None,
    "total_laps": None,
    "world_position_x": None, "world_position_z": None,
    "longitudinal_g": None,
    "wheel_speed": [None] * 4, "wheel_slip_ratio": [None] * 4,
    "tyres_wear": [None] * 4, "tyre_compound": "Unknown", "tyres_age_laps": None,
    "track_id": None, "session_type": None, "game_mode": None, "session_uid": None,
    "formula": None, "player_car_index": None,
    "season_link_identifier": None, "weekend_link_identifier": None,
    "session_link_identifier": None,
    "packet_format": None, "game_year": None,
    "raw_packet_format": None, "raw_game_year": None,
    "edition_detection": "unknown", "udp_configuration_warning": None,
    "season_pack_detected": False, "season_pack_detection": None,
    "f1_25_detected": False,
    "num_active_cars": None, "participant_team_ids": [],
    "pit_status": 0, "lap_invalid": False, "paused": False,
    "drs": 0, "aero": 0, "aero_mode": 0,
    "active_aero_available": 0, "active_aero_activation_distance": 0,
    "boost_active": 0, "overtake_available": 0, "overtake_active": 0,
    "overtake_activation_distance": 0, "regulations_2026": 0, "driving_wrong_way": 0,
    "telemetry2_received": False,
    "ers_mode": 0, "ers_percent": 0,
    "ers_store_energy_j": None,
    "fuel_in_tank_kg": None, "fuel_capacity_kg": None, "fuel_remaining_laps": None,
    "game_version": "unknown",
    "car_setup": None,
}
latest = copy.deepcopy(DEFAULT_TELEMETRY_STATE)
