latest = {
    "speed": 0,
    "gear": 0,
    "throttle": 0,
    "brake": 0,
    "steer": 0,
    "rpm": 0,
    "lap_time": "--:--.---",
    "drs": 0,
    "aero": 0,
    "aero_mode": 0,
    "aero_available": 0,
    "aero_distance": 0,
    "overtake_active": 0,
    "ers": 0,
    "ers_percent": 0,
    "updated": 0,
    "game_version": "unknown",
}